# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: gradle build

      - name: Publish to GitHub Packages
        run: gradle publishS2protocolPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_KEY: ${{ secrets.GITHUBKEY }}

      - name: Publish to Bintray
        run: gradle bintrayUpload
        env:
          BINTRAY_USER: jhonnold
          BINTRAY_KEY: ${{ secrets.BINTRAYKEY }}
